### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by NetWin** [NetWin/date-time-picker#3]
This is a non exclusive list of things i want to change / i've already done in this repository. 
There is no specific timeframe yet but i expect this stuff to be done definitely by the end of this year

### Planned changes / features for the near future or in active development
- [x] Introduce [ng-doc](https://ng-doc.com/)
  - In order to improve Component documentation
  - Include Demos and interative Playgrounds
- [ ] Add issue  / PR templates, 
- [ ] Maybe Look into Github Projects (probably not necessary though)
- [x] Add [commitlint](https://commitlint.js.org/)
- [x] Convert all components to Standalone
  - Drop all the modules (where it makes sense)
  - Only export Components that are relevant to consumers
- [ ] Remove UnixDateTimeAdapter 
  - Just use date and convert them yourself if needed
  - We'll probably be able to remove all the generic `T` declarations internally and just use `Date` instead
- [x] Remove the datepicker directive that opens a angular material popup
    - If you need a popup, just build your own and embed the inline picker
  - ...
- [ ] Cleanup the component styles
  -  When removing the material popup, the necessity of providing global styles will probably be removed and we can finally just use component styles

### Planned changes / feature for the medium / distant future 
- [ ] Introduce strict mode
- [ ] Look into automatic dependency update notifications á la Renovate
- Look over issues within the source repository (https://github.com/danielmoncada/date-time-picker/issues)

### Stuff i already did
- Update Linter (TSLint -> [ESLint](https://eslint.org/))
- Fix hundrets of linter warnings
- Introduce automatic publishing via [Semantic-Release](https://semantic-release.gitbook.io/semantic-release) within Github actions
  - `master` branch automatically releases a production / latest release
  - `release/*` branches automatically deploy `rc` releases
- Automatic code formatting using [prettier](https://prettier.io/) 
  - I'm personally not a fan of prettier itself but i can acknowledge the importance / usefulnes of unified automatic code formatting within an public /open source repo
- Automatic Linting / Formatting in a pre-commit hook using [lint-staged](https://github.com/lint-staged/lint-staged) and [husky](https://typicode.github.io/husky/)
